# Generated by Django 2.0.13 on 2019-06-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='slug',
            field=models.SlugField(default='default'),
        ),
    ]
