# Generated by Django 2.0.13 on 2019-06-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_problems_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allpoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(unique=True)),
                ('korea_points', models.PositiveIntegerField(default=0)),
                ('yonsei_points', models.PositiveIntegerField(default=0)),
                ('others_points', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
