# Generated by Django 2.0.13 on 2019-06-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_allpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='answer',
            field=models.CharField(default='.', max_length=200),
        ),
    ]
