# Generated by Django 2.0.13 on 2019-06-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_problems_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpoints',
            name='datetime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
