# Generated by Django 2.0.13 on 2019-06-22 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190623_0611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply',
            new_name='author',
        ),
    ]
