# Generated by Django 2.0.13 on 2019-06-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_profile_univ'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('korea', '고려대'), ('yonsei', '연세대'), ('others', '그외')], default='others', max_length=30),
        ),
    ]
