# Generated by Django 2.0.13 on 2019-06-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_auto_20190623_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='problem_check',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
