# Generated by Django 2.0.13 on 2019-06-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_auto_20190623_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='problem_check',
        ),
    ]
